name: Project Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - merged
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Clean up old node_modules and lock file
        run: |
          rm -rf node_modules
          rm -f package-lock.json
      
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      
      - name: Install Dependencies with Legacy Peer Deps
        run: npm install --legacy-peer-deps || npm install --legacy-peer-deps --force

      - name: Build Project Locally
        run: npm run build

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: Deploy Project Artifacts to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: vercel deploy --prebuilt --prod
